### PR TITLE
libvterm support for isend-mode

### PR DESCRIPTION
**Pull request by Blade6570**
Hi, 

I have added the support for vterm which is now being widely used as the terminal emulator for emacs. For my use cases it works like ansi-term so merge it if you feel ilike.  

Fixes: #15

### CODE REVIEW

**Comment by ffevotte** [comment]
Many thanks for this! I just installed `vterm` to be able to test you PR; I'll try to look at it and merge it shortly.

Seeing the (ever increasing) number of (slightly incompatible)
- terminal types, and
- interpreters
that we'd like `isend` to support, I'm considering restructuring the code in order to make it easier to extend. Adding `vterm` support  might be an excellent occasion to do so.

Thanks, in any case!

**Comment by ffevotte** [comment]
Hi @Blade6570,

I extended your PR in #17, introducing a cleaner separation between terminal-specific parts of the implementation. In particular, this should fixe a few quirks I had when using `isend` with `vterm`. Most notably: sent lines were inserted once at the beginning of the terminal buffer, and an other time at the prompt.

Could you please test that version (#17) and report back if it breaks anything?
Out of curiosity, what are you using `isend` for? If you're using it to interact with a python interpreter, I'd be especially interested to hear about your feedback.

**Comment by Blade6570** [comment]
Hi @ffevotte, 

I have checked the modified PR in https://github.com/ffevotte/isend-mode.el/pull/17 and it works as expected in the vterm now. can it be merged now? 

About my use-case, I mostly use it for interactive python and it works well by adding `(add-hook 'isend-mode-hook 'isend-default-ipython-setup)` to the init file. Sometimes I try to move text between two text buffers using `isend` but then the  initial `ipython` setting does not allow me to do that. As far as I understand, I have to change the init file again to restore the default behavior of `isend`. Is there any other way of doing this that I have missed?  

if not then I am thinking to create functions like `isend-associate, isend-associate-ipython, isend-associate-shell` where users can select the behaviour they want while choosing the destination buffer.  Let me know if it makes sense to do this way.

**Comment by ffevotte** [comment]
> I have checked the modified PR in #17 and it works as expected in the vterm now. can it be merged now?

Thanks! My local tests went well, too. I just merged the PRs. Melpa should update soon, I think.

<br/>

> About my use-case, I mostly use it for interactive python and it works well by adding `(add-hook 'isend-mode-hook 'isend-default-ipython-setup)` to the init file.

Thanks for the answer? I'm wondering whether anyone uses Python with `isend-default-python-setup`: it looked like it was broken when I tried to test all possible use cases with #17...

> Sometimes I try to move text between two text buffers using `isend` but then the initial `ipython` setting does not allow me to do that. As far as I understand, I have to change the init file again to restore the default behavior of `isend`. Is there any other way of doing this that I have missed?

You're right that it's not easy ATM. I guess the easiest solution for now would be to have an `isend-plain-setup` command, that you could issue to reset the configuration when you want to send to a "normal" buffer. With something like this in your init file:
```
(defun isend-plain-setup ()
  (interactive)
  (set (make-local-variable 'isend-skip-empty-lines)     t)
  (set (make-local-variable 'isend-strip-empty-lines)    nil)
  (set (make-local-variable 'isend-delete-indentation)   nil)
  (set (make-local-variable 'isend-end-with-empty-line)  nil)
  (set (make-local-variable 'isend-bracketed-paste)      nil)
  (set (make-local-variable 'isend-send-line-function)   nil)
  (set (make-local-variable 'isend-send-region-function) nil)
  (set (make-local-variable 'isend-mark-defun-function)  #'mark-defun))
```
you should be able to get the behavior you want like so:
1. <kbd>M-x</kbd> `isend ` <kbd>RET</kbd> `your-buffer-name` <kbd>RET</kbd>
2. <kbd>M-x</kbd> `isend-plain-setup` <kbd>RET</kbd>

<br/>

> if not then I am thinking to create functions like isend-associate, isend-associate-ipython, isend-associate-shell where users can select the behaviour they want while choosing the destination buffer. Let me know if it makes sense to do this way.

I really like this idea! Expanding on it a little, I could imagine `isend`/`isend-associate` taking an optional prefix argument: when you call it normally, it would automatically choose the default behavior depending on the current buffer mode. But with a prefix argument, it could ask the user to choose between a set of standard "profiles".

This is more work, but I think it would bring a lot of advantages. First, it would allow python users to set up `isend` to use `ipython` by default, but temporarily switch to a `python` "profile" when needed (provided the latter works, of course). And of course it would also work nicely for your use case, allowing you to opt for a `plain` "profile" instead of the default `ipython` when sending to regular buffers.

We could also ship `isend-mode` with a set of standard "profiles" covering most needs, but make it so that users can easily add custom profiles to choose from.

**Comment by ffevotte** [comment]
Also, I'm afraid that, with this PR being now closed, I'll forget about this discussion... If you're interested in talking about this further, or simply want to increase the chance that such a feature appears in `isend-mode` one day, would you please open a specific issue for it? TIA

**Pull request merged**
